game:
  canvas:
    width: 400
    height: 300


server:
  port: 8081

logging:
  level:
    root: info
    com.example.demo: debug
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
